### ISSUE TITLE
What about grouping the sample per service category ?

### ISSUE THREAD

**Issue by agoncal** [Azure-Samples/java-on-azure-examples#138]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Mention any other details that might be useful

The samples are all ordered by service (e.g. AKS, CosmosDB...) and not by service category (e.g. Compute, Databases...) which then end up following an alphabetical order:

```
aci/
acr/
adx/
aks/
appservice/
aro/
cosmosdb/
eventhubs/
functions/
group/
keyvault/
mssql/
mysql/
postgresql/
redis/
servicebus/
spring-cloud/
storage/
```

If you look at something like [Azure Charts](https://azurecharts.com/overview), the services are ordered per category:

```
AI + Machine Learning
Analytics
Compute
Databases
Development
Identity + Security
IoT + MR
Integration
Management + Governance
Media + Comms
Migration
Networking
Storage
```

What about reordering the samples and grouping them by category ? We could end up, either with an extra directory:

```
analytics/
  adx/
  eventhubs/
compute/
  aci/
  acr/
  aks/
  appservice/
  aro/
  functions/
core/
  group/
databases/
  cosmosdb/
  mssql/
  mysql/
  postgresql/
  redis/
development/
  spring-cloud/
integration/
  servicebus/
security/
  keyvault/
storage/
  storage/
```

Or with a prefix of the category:

```
analytics-adx/
analytics-eventhubs/
compute-aci/
compute-acr/
compute-aks/
compute-appservice/
compute-aro/
compute-functions/
core-group/
databases-cosmosdb/
databases-mssql/
databases-mysql/
databases-postgresql/
databases-redis/
development-spring-cloud/
integration-servicebus/
security-keyvault/
storage-storage/
```

We can even flatten the entire structure:

```
analytics-adx-create-database/
analytics-adx-create-table/
analytics-adx-create/
analytics-adx-ingest-client/
analytics-eventhubs-create-eventhub/
analytics-eventhubs-create-namespace/
analytics-eventhubs-receive-event/
analytics-eventhubs-send-event
...
```

**Comment by mnriem** [comment]
I would have no problem with reordering. Just not by what Azure Charts does, but rather by what the Azure Portal does as that is the official source. Note that if you do the reordering you will have to take into account that all the READMEs need to be touched ;)

**Comment by agoncal** [comment]
Yes, it makes sense to take the official Azure Portal organization.

So @mnriem, what do you like the best ?

1) Extra Sub directories

```
analytics/
  adx/
    create-database/
    eventhubs/
  eventhubs/
```

2) Sub directories 

```
analytics-adx/
    create-database/
    eventhubs/
analytics-eventhubs/
```

3) Flat structure

```
analytics-adx-create-database/
analytics-adx-eventhubs/
analytics-eventhubs-create/
```

I quite like the flat structure (it's also easier to point at external files/readmes in terms of relative paths) but it can quickly end up having hundreds of directories (one per example)

**Comment by mnriem** [comment]
@agoncal For me it would be 1.
