### ISSUE TITLE
Add "Azure Container Apps" example

### ISSUE THREAD

**Issue by agoncal** [Azure-Samples/java-on-azure-examples#209]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

See:

* #121 
* #122
* #123

### Mention any other details that might be useful

Azure Container Apps is still in preview but we could add a few sample on how to create a container app, a log environment, deploy an image, etc.

**Comment by mnriem** [comment]
Closing this in favor of #123
