### ISSUE TITLE
Upgrading to the latest Azure SDK version 1.2.30 ?

### ISSUE THREAD

**Issue by agoncal** [Azure-Samples/java-on-azure-examples#502]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I'm trying to run the Service Bus samples with the new [Service bus emulator](https://learn.microsoft.com/en-us/azure/service-bus-messaging/test-locally-with-service-bus-emulator). Unfortunately, with the current Azure SDK version (`<azure.bom.version>1.2.3</azure.bom.version>`) the connection string (`Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;`) is not recognized. I've tried with the latest [1.2.30 version](https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.2.30) and the connection string is recognized.

What about updating the Azure SDK version ?

See https://github.com/Azure-Samples/java-on-azure-examples/pull/503

**Comment by mnriem** [comment]
Go for it!
