### ISSUE TITLE
<appName> only allow alphanumeric characters

### ISSUE THREAD

**Issue by agoncal** [Azure-Samples/java-on-azure-examples#99]
When trying to deploy the `javase-quarkus` sample with the Azure Maven plugin, I get an error that the `<appName> only allow alphanumeric characters`. That's because, in this example, the `example.postfix` variable is not set and you end up with a wrong app name:

```
<appName>javase-quarkus-${example.postfix}</appName>
```

To fix it it's just a matter of adding the variable:

```
<example.postfix>${maven.build.timestamp}</example.postfix>
<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
<appName>javase-quarkus-${example.postfix}</appName>
```

The variable is actually defined in `spring-cloud/helloworld/pom.xml` but maybe should be defined in the parent pom.

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Once you've packaged the Quarkus application with `mvn package` you follow the readme and deploy the app with:

```
 mvn azure-webapp:deploy \
                                               -DappName=$APPSERVICE_JAVASE_QUARKUS \
                                               -DappServicePlan=$APPSERVICE_PLAN \
                                               -DresourceGroup=$RESOURCE_GROUP
```

Then you get the error.

### Any log messages given by the failure

```
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.12.0:deploy (default-cli) on project appservice-javase-quarkus: The <appName> only allow alphanumeric characters, hyphens and cannot start or end in a hyphen.
```

**Comment by mnriem** [comment]
Can you create a PR for it and address it whatever other examples it also shows up? Can you pull it up into the top-level parent POM for the modules where that can be done. Thanks!
